In [1]:
import pandas as pd
import numpy as np

In [2]:
data_descriptions = pd.read_csv('../data/data_descriptions.csv')
pd.set_option('display.max_colwidth', None)
data_descriptions

,Column_name,Column_type,Data_type,Description
0,subscription_id,Identifier,character,Unique identifier of each subscription
1,observation_dt,Identifier,date,The date on which the subscription was observed to calculate the features in the dataset. It was chosen at random amongst all the dates between the start of the subscription and the end of the subscription (before cancellation)
2,is_retained,Target,Integer,"TRAINING SET ONLY! 0 = the learner cancelled their subscription before next payment, 1 = the learner made an additional payment in this subscription"
3,specialization_id,Feature - Specialization Info,character,Unique identifier of a specialization (each subscription gives a learner access to a particular specialization)
4,cnt_courses_in_specialization,Feature - Specialization Info,integer,number of courses in the specialization
5,specialization_domain,Feature - Specialization Info,character,"primary domain of the specialization (Computer Science, Data Science, etc.)"
6,is_professional_certificate,Feature - Specialization Info,boolean,"BOOLEAN for whether the specialization is a ""professional certicate"" (a special type of specialization that awards completers with an industry-sponsored credential)"
7,is_gateway_certificate,Feature - Specialization Info,boolean,"BOOLEAN for whether the specialization is a ""gateway certificate"" (a special type of specialization geared towards learners starting in a new field)"
8,learner_days_since_registration,Feature - Learner Info,integer,Days from coursera registration date to the date on which the observation is made
9,learner_country_group,Feature - Learner Info,character,"the region of the world that the learner is from (United States, East Asia, etc.)"
10,learner_gender,Feature - Learner Info,character,"the reported gender of the learner (if not available, then ""unknown"")"
11,learner_cnt_other_courses_active,Feature - Learner Info,integer,Other courses (not in this specialization) in which the learner was active prior to observation_dt
12,learner_cnt_other_courses_paid_active,Feature - Learner Info,integer,Other courses (not in this specialization) in which the learner was active prior to observation_dt and was a paid enrollee
13,learner_cnt_other_courses_items_completed,Feature - Learner Info,integer,Items completed in other courses (not in this specialization) prior to the observation_dt
14,learner_cnt_other_courses_paid_items_completed,Feature - Learner Info,integer,"Items completed in other courses (not in this specialization) prior to the observation_dt, where the learner was a paid enrollee"
15,learner_cnt_other_transactions_past,Feature - Learner Info,integer,Other payments that the learner made on Coursera separate from this subscription
16,learner_other_revenue,Feature - Learner Info,numeric,US Dollar estimate of other payments that the learner made on Coursera separate from this subscription
17,subscription_period_order,Feature - Subscription Status,integer,"An index of the ""month"" of the subcription; 1 = first month of payment, 2 = second month of payment"
18,days_since_last_payment,Feature - Subscription Status,integer,Days since the last payment in the subscription
19,days_til_next_payment_due,Feature - Subscription Status,integer,Days until the next payment in the subsciption is due
20,cnt_enrollments_started_before_payment_period,Feature - Prior Subscription Activity,integer,Courses in the subscription specialization that were enrolled prior to the start of this subscription period
21,cnt_enrollments_completed_before_payment_period,Feature - Prior Subscription Activity,integer,Courses in the subscription specialization that were completed prior to the start of this subscription period
22,cnt_enrollments_active_before_payment_period,Feature - Prior Subscription Activity,integer,Courses in the subscription specialization that were active prior to the start of this subscription period
23,cnt_items_completed_before_payment_period,Feature - Prior Subscription Activity,integer,Items in the subscription specialization that were completed prior to the start of the subscription period
24,cnt_graded_items_completed_before_payment_period,Feature - Prior Subscription Activity,integer,Graded items (assignments) in the subscription speciallzation that were completed prior to the start of the subscription period
25,is_subscription_started_with_free_trial,Feature - Prior Subscription Activity,boolean,BOOLEAN for whether or not the subscription started with a free trial (7-day period for the learner to sample the specialization before paying)
26,cnt_enrollments_started_during_payment_period,Feature - Current Subscription Activity,integer,Courses in the subscription specialization that were enrolled during this subscription period (before observation_dt)
27,cnt_enrollments_completed_during_payment_period,Feature - Current Subscription Activity,integer,Courses in the subscription specialization that were completed during this subscription period (before observation_dt)
28,cnt_enrollments_active_during_payment_period,Feature - Current Subscription Activity,integer,Courses in the subscription specialization that were active during this subscription period (before observation_dt)
29,cnt_items_completed_during_payment_period,Feature - Current Subscription Activity,integer,Items in the subscription specialization that were completed during this subscription period (before observation_dt)
30,cnt_graded_items_completed_during_payment_period,Feature - Current Subscription Activity,integer,Graded items (assignments) in the subscription speciallzation that were completed during this subscription period (before observation_dt)
31,is_active_capstone_during_pay_period,Feature - Current Subscription Activity,boolean,"BOOLEAN for whether the learner was active in a capstone course during this subscription period. The last course in some specializations is called a ""captone"" course as allows the learner to apply the skills they have learned in the prior courses up to that point."
32,sum_hours_learning_before_payment_period,Feature - Current Subscription Activity,numeric,Hours spent learning in subscription specialization courses prior to the subscription period
33,sum_hours_learning_during_payment_period,Feature - Current Subscription Activity,numeric,Hours spent learning in subscription specialization courses during the subscription period (before observation_dt)
34,cnt_days_active_before_payment_period,Feature - Current Subscription Activity,integer,Days active in the subscription specialization prior to the subscription period
35,cnt_days_active_during_payment_period,Feature - Current Subscription Activity,integer,Days active thus far in the subscription period (before observation_dt)
36,cnt_days_since_last_activity,Feature - Current Subscription Activity,integer,"Days since the most recent activity date in the subscription (if never active, defaults to the number of days since the start of the subscription)"

#### load the data

In [41]:
dataset = pd.read_csv("../data/dataset.csv", low_memory = False)
# dataset.info()

In [42]:
dataset.shape

(413955, 37)

In [32]:
dataset.isna().values.ravel().sum()

np.int64(36)

There are only 36 missing values in the data, I will remove the rows that are missing values and and carry on the analysis.

In [36]:
dataset.isnull().sum().to_frame()

                                                  0
subscription_id                                   0
observation_dt                                    0
is_retained                                       1
specialization_id                                 1
cnt_courses_in_specialization                     1
specialization_domain                             2
is_professional_certificate                       1
is_gateway_certificate                            1
learner_days_since_registration                   1
learner_country_group                             1
learner_gender                                    1
learner_cnt_other_courses_active                  1
learner_cnt_other_courses_paid_active             1
learner_cnt_other_courses_items_completed         1
learner_cnt_other_courses_paid_items_completed    1
learner_cnt_other_transactions_past               1
learner_other_revenue                             1
subscription_period_order                         1
days_since_last_payment                           1
days_til_next_payment_due                         1
cnt_enrollments_started_before_payment_period     1
cnt_enrollments_completed_before_payment_period   1
cnt_enrollments_active_before_payment_period      1
cnt_items_completed_before_payment_period         1
cnt_graded_items_completed_before_payment_period  1
is_subscription_started_with_free_trial           1
cnt_enrollments_started_during_payment_period     1
cnt_enrollments_completed_during_payment_period   1
cnt_enrollments_active_during_payment_period      1
cnt_items_completed_during_payment_period         1
cnt_graded_items_completed_during_payment_period  1
is_active_capstone_during_pay_period              1
sum_hours_learning_before_payment_period          1
sum_hours_learning_during_payment_period          1
cnt_days_active_before_payment_period             1
cnt_days_active_during_payment_period             1
cnt_days_since_last_activity                      1

In [43]:
# drop na values from the data
dataset = dataset.dropna()

In [ ]:
# split into training, validation and test set

In [49]:
# remove outliers from training data
dataset.quantile(q = 0.25, numeric_only = True)

is_retained                                          0.00
cnt_courses_in_specialization                        5.00
learner_days_since_registration                     71.00
learner_cnt_other_courses_active                     0.00
learner_cnt_other_courses_paid_active                0.00
learner_cnt_other_courses_items_completed            0.00
learner_cnt_other_courses_paid_items_completed       0.00
learner_cnt_other_transactions_past                  0.00
learner_other_revenue                                0.00
subscription_period_order                            1.00
days_since_last_payment                              5.00
days_til_next_payment_due                           10.00
cnt_enrollments_started_before_payment_period        1.00
cnt_enrollments_completed_before_payment_period      0.00
cnt_enrollments_active_before_payment_period         1.00
cnt_items_completed_before_payment_period            7.00
cnt_graded_items_completed_before_payment_period     0.00
cnt_enrollments_started_during_payment_period        0.00
cnt_enrollments_completed_during_payment_period      0.00
cnt_enrollments_active_during_payment_period         0.00
cnt_items_completed_during_payment_period            0.00
cnt_graded_items_completed_during_payment_period     0.00
sum_hours_learning_before_payment_period             1.15
sum_hours_learning_during_payment_period             0.00
cnt_days_active_before_payment_period                2.00
cnt_days_active_during_payment_period                0.00
cnt_days_since_last_activity                         1.00
Name: 0.25, dtype: float64